steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/contiunousi/web:$SHORT_SHA','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/contiunousi/web:$SHORT_SHA']

